# fly.toml app configuration file generated for yipadaa on 2023-08-17T00:16:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yipadaa"
primary_region = "ams"

[build]

[env]
  PORT = 9090

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
